[build]
  publish = "."

[[redirects]]
  from = "/admin/config.yml"
  to = "/admin/config.yml"
  status = 200
  force = true

[[redirects]]
  from = "/posts.json"
  to = "/posts.json"
  status = 200
  force = true
