backend:
  name: github
  repo: megyeri0530-arch/konczosmonikaweb
  branch: main
  auth_methods: [token, oauth]
  base_url: https://xn--llekfny-byae.com
  auth_endpoint: api/auth

media_folder: "picture"
public_folder: "picture"

collections:
  - name: "blog"
    label: "Lélek-gondolatok"
    files:
      - label: "Összes Lélek-gondolat Bejegyzés"
        name: "posts_list"
        file: "posts.json"
        fields:
          - label: "Bejegyzések"
            name: "posts"
            widget: "list"
            summary: "{{fields.title}} - {{fields.date}}"
            fields:
              - {label: "Azonosító (ID)", name: "id", widget: "string"}
              - {label: "Cím", name: "title", widget: "string"}
              - {label: "Dátum", name: "date", widget: "datetime", format: "YYYY.MM.DD", date_format: "YYYY.MM.DD", time_format: false}
              - {label: "Szerző", name: "author", widget: "string", default: "Konczosné Megyeri Mónika"}
              - {label: "Kategória", name: "category", widget: "select", options: ["Lélek-gondolatok", "Angyali Útmutatás", "Expanse Therapy®", "Önismeret"]}
              - {label: "Bejegyzés Borítóképe", name: "image", widget: "image", default: "picture/ethereal_angel_hero_bg.png", media_folder: "picture", public_folder: "picture"}
              - {label: "Rövid összefoglaló", name: "excerpt", widget: "text"}
              - {label: "Bejegyzés tartalma", name: "body", widget: "markdown"}
